# Generated by Django 3.0.4 on 2021-06-11 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(default='resume_images/default_resume_image.jpg', upload_to='resume_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('TR', 'Стажер'), ('JR', 'Джуноир'), ('MD', 'Мидл'), ('SR', 'Синьор'), ('TM', 'Тимлид')], default='TR', max_length=10, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='image',
            field=models.ImageField(upload_to='speciality_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 9, 15, 19, 547629), verbose_name='Опубликовано'),
        ),
    ]
